source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
use_modular_headers!

target 'XKProjectHelper_Example' do
  pod 'XKProjectHelper', :path => '../'

  target 'XKProjectHelper_Tests' do
    inherit! :search_paths

    
  end
end
